-- Write query to create the new tables in your database based on the ERD provided
create table authors (
  author_id integer PRIMARY KEY generated by default AS identity,
  author_name varchar(255),
  nationality varchar(255)
);