-- Write query to create the new tables in your database based on the ERD provided
create table genres (
  genre_id integer PRIMARY KEY generated by default AS identity,
  genre_name varchar(100),
  nationality varchar(255)
);